// Map a reconciled scope to PayPal's invoice shape.
//
// The toolkit's create_invoice takes flat top-level fields (currency_code, invoice_number, note,
// invoicer_*) plus PayPal's real nested `primary_recipients` and `items`. Contract confirmed by a
// live sandbox draft on 2026-10-08 (docs/t02-probe.md). Only billable lines reach the invoice.
import type { Reconciliation } from "./scope";

export interface InvoiceTarget {
  invoiceNumber: string;
  buyerEmail: string;
  invoicer?: { businessName?: string; givenName?: string; surname?: string; emailAddress?: string };
}

export interface PaypalInvoiceDraft {
  currency_code: string;
  invoice_number: string;
  note: string;
  primary_recipients: { billing_info: { email_address: string } }[];
  items: { name: string; quantity: string; unit_amount: { currency_code: string; value: string } }[];
  invoicer_business_name?: string;
  invoicer_given_name?: string;
  invoicer_surname?: string;
  invoicer_email_address?: string;
}

export function toPaypalInvoice(r: Reconciliation, target: InvoiceTarget): PaypalInvoiceDraft {
  const billable = [...r.quoted, ...r.confirmed];
  if (billable.length === 0) throw new Error("nothing billable to invoice");
  const draft: PaypalInvoiceDraft = {
    currency_code: r.currency,
    invoice_number: target.invoiceNumber,
    note: "Generated by ScopeLedger from the confirmed scope.",
    primary_recipients: [{ billing_info: { email_address: target.buyerEmail } }],
    items: billable.map((line) => ({
      name: line.description.slice(0, 100),
      quantity: "1",
      unit_amount: { currency_code: r.currency, value: (line.amountCents / 100).toFixed(2) },
    })),
  };
  if (target.invoicer) {
    if (target.invoicer.businessName) draft.invoicer_business_name = target.invoicer.businessName;
    if (target.invoicer.givenName) draft.invoicer_given_name = target.invoicer.givenName;
    if (target.invoicer.surname) draft.invoicer_surname = target.invoicer.surname;
    if (target.invoicer.emailAddress) draft.invoicer_email_address = target.invoicer.emailAddress;
  }
  return draft;
}

/**
 * The invoice id from the toolkit's response. The tool returns `{ rel, href, method }`, but through
 * the AI SDK wrapper it can arrive as a JSON string, so accept both.
 */
export function invoiceIdFrom(result: unknown): string {
  let value: unknown = result;
  if (typeof value === "string") {
    try {
      value = JSON.parse(value);
    } catch {
      /* not JSON; fall through and read the raw string */
    }
  }
  const href =
    typeof value === "object" && value !== null && "href" in value
      ? String((value as { href: unknown }).href)
      : String(value);
  const id = href.split("/invoices/")[1]?.split(/[/"?#\s]/)[0];
  if (!id || !id.startsWith("INV2-")) throw new Error(`could not read an invoice id from: ${href.slice(0, 120)}`);
  return id;
}
